extends Node

# The core brain of the "Butterfly Effect" system.
# This singleton manages the global economy, procedural Oligarchs,
# generated regions, and event ripples.

# ---------------------------------------------------------
# SIGNALS
# ---------------------------------------------------------
signal event_triggered(action_id: String, target: String)
signal world_state_changed()
signal netfeed_event_generated(event_data: Dictionary)
signal oligarch_action_taken(action: Dictionary)

# ---------------------------------------------------------
# NETFEED (The Internet/Communication Array)
# ---------------------------------------------------------
var netfeed_history = [] # Stores { "type": String, "headline": String, "timestamp": int }

# ---------------------------------------------------------
# GLOBAL ECONOMY STATE
# ---------------------------------------------------------
var global_economy = {
	"food_price": 100,
	"tech_price": 500,
	"security_presence": 50, # 0 (None) to 100 (Martial Law)
	"public_tension": 20, # 0 (Docile) to 100 (Rioting)
	"senate_alignment": 50 # 0 (Fully Pro-Sinks) to 100 (Fully Pro-Enclave)
}

# ---------------------------------------------------------
# PROCEDURAL OLIGARCHS — Generated at playthrough start
# ---------------------------------------------------------
var oligarchs: Array[OligarchData] = []

# Oligarch generation pools
var _oligarch_first_names = [
	"Viktor", "Helena", "Marcus", "Elara", "Cassius", "Nadia",
	"Theron", "Isolde", "Dorian", "Valentina", "Lucius", "Petra"
]
var _oligarch_last_names = [
	"Voss", "Kaine", "Ashford", "Moreau", "Sterling", "Drakenfeld",
	"Oberon", "Crane", "Blackwell", "Montague", "Harken", "Solaris"
]
var _oligarch_titles = ["CEO", "Chairman", "Director-General", "Founder", "Executive Chancellor", "Chief Architect"]
var _oligarch_sectors = ["Food", "Tech", "Security", "Media", "Pharma", "Energy"]

var _oligarch_ambition_pool = [
	"Monopolize supply", "Achieve political immortality", "Build a legacy",
	"Escape", "Crush the resistance", "Control the narrative",
	"Transcend humanity", "Purge The Sinks"
]

var _oligarch_quirks = [
	"Never seen without dark glasses", "Speaks in rehearsed soundbites",
	"Collects extinct animal specimens", "Known for explosive temper tantrums",
	"Eerily calm, never raises voice", "Obsessed with ancient Roman history",
	"Rumored to have body doubles", "Always accompanied by a personal AI",
	"Publicly vegetarian, privately hunts", "Wears the same outfit every day",
	"Laughs at their own jokes, alone", "Speaks about themselves in third person",
	"Has a visible cybernetic enhancement", "Donates to charity on camera only",
	"Known insomniac, sends messages at 3AM", "Pathological liar, even about small things"
]

# ---------------------------------------------------------
# PROCEDURAL REGIONS — Generated at playthrough start
# ---------------------------------------------------------
var current_region: String = ""

func _ready():
	print("WorldDirector initialized. Economy online.")

# =============================================================
# PLAYTHROUGH INITIALIZATION
# =============================================================

func initialize_playthrough() -> void:
	_generate_oligarchs()
	
	# Regions are generated by RegionGenerator singleton
	if has_node("/root/RegionGenerator"):
		var region_gen = get_node("/root/RegionGenerator")
		region_gen.generate_world()
		current_region = region_gen.starting_region
		
		# Assign oligarchs to regions they control
		_assign_oligarch_territories(region_gen)
	
	# NPC roster is generated by PopulationDirector singleton
	if has_node("/root/PopulationDirector"):
		get_node("/root/PopulationDirector").generate_new_roster()
	
	print("Playthrough initialized. %d Oligarchs. Current region: %s" % [oligarchs.size(), current_region])

func _generate_oligarchs() -> void:
	oligarchs.clear()
	
	_oligarch_first_names.shuffle()
	_oligarch_last_names.shuffle()
	_oligarch_titles.shuffle()
	_oligarch_sectors.shuffle()
	_oligarch_quirks.shuffle()
	_oligarch_ambition_pool.shuffle()
	
	var oligarch_count = randi_range(4, 6)
	var quirk_index = 0
	var ambition_index = 0
	
	for i in range(oligarch_count):
		var o = OligarchData.new()
		o.oligarch_id = "oligarch_%d" % i
		o.oligarch_name = _oligarch_first_names[i] + " " + _oligarch_last_names[i]
		o.title = _oligarch_titles[i % _oligarch_titles.size()]
		o.sector_of_influence = _oligarch_sectors[i]
		
		# Randomize intrinsic traits
		o.ruthlessness = randf()
		o.vanity = randf()
		o.paranoia_base = randf()
		o.intelligence = randf()
		o.greed = randf()
		o.ideology = randf()
		
		# Starting wealth varies by sector
		match o.sector_of_influence:
			"Tech": o.wealth = randi_range(2000000, 4000000)
			"Food": o.wealth = randi_range(800000, 1500000)
			"Security": o.wealth = randi_range(400000, 800000)
			"Media": o.wealth = randi_range(600000, 1200000)
			"Pharma": o.wealth = randi_range(1500000, 3000000)
			"Energy": o.wealth = randi_range(1000000, 2500000)
		
		# Starting dynamic state
		o.paranoia = o.paranoia_base * 30.0
		o.public_image = randf_range(-20.0, 50.0)
		o.controversy_level = randf_range(0.0, 20.0)
		o.political_influence = randf_range(30.0, 80.0)
		
		# Assign 1-2 ambitions
		var num_ambitions = randi_range(1, 2)
		for a in range(num_ambitions):
			if ambition_index < _oligarch_ambition_pool.size():
				o.ambitions.append(_oligarch_ambition_pool[ambition_index])
				o.ambition_progress[_oligarch_ambition_pool[ambition_index]] = 0.0
				ambition_index += 1
		
		# Assign 1-2 quirks
		var num_quirks = randi_range(1, 2)
		for q in range(num_quirks):
			if quirk_index < _oligarch_quirks.size():
				o.quirks.append(_oligarch_quirks[quirk_index])
				quirk_index += 1
		
		oligarchs.append(o)
		print("  Generated: %s %s — %s of %s [%s]" % [o.oligarch_name, o.title, o.title, o.sector_of_influence, ", ".join(o.ambitions)])

func _assign_oligarch_territories(region_gen) -> void:
	# Link oligarchs to regions matching their sector type
	for o in oligarchs:
		match o.sector_of_influence:
			"Food":
				var farms = region_gen.get_regions_by_type("AGRICULTURAL")
				if farms.size() > 0:
					farms[0]["connected_oligarch"] = o.oligarch_id
			"Security":
				var transits = region_gen.get_regions_by_type("TRANSIT")
				if transits.size() > 0:
					transits[0]["connected_oligarch"] = o.oligarch_id
			"Tech", "Pharma", "Energy":
				var industry = region_gen.get_regions_by_type("INDUSTRIAL")
				for region in industry:
					if region["connected_oligarch"] == "":
						region["connected_oligarch"] = o.oligarch_id
						break
			"Media":
				var elite = region_gen.get_regions_by_type("URBAN_ELITE")
				if elite.size() > 0:
					elite[0]["connected_oligarch"] = o.oligarch_id

# =============================================================
# WORLD CYCLE — Called each tick to evolve everything
# =============================================================

func run_world_cycle() -> void:
	_evolve_oligarchs()
	
	# Evolve NPCs
	if has_node("/root/PopulationDirector"):
		get_node("/root/PopulationDirector").evolve_all_npcs(global_economy)
	
	_update_region_dynamics()
	_check_systemic_collapse()
	world_state_changed.emit()

func _evolve_oligarchs() -> void:
	for o in oligarchs:
		var actions = o.process_world_state(global_economy, oligarchs)
		for action in actions:
			_apply_oligarch_action(action)
			oligarch_action_taken.emit(action)

func _apply_oligarch_action(action: Dictionary) -> void:
	var impact = action.get("impact", {})
	
	if impact.has("security_presence"):
		global_economy["security_presence"] = clamp(
			global_economy["security_presence"] + impact["security_presence"], 0, 100)
	if impact.has("tension_increase"):
		global_economy["public_tension"] = clamp(
			global_economy["public_tension"] + impact["tension_increase"], 0, 100)
	if impact.has("tension_decrease"):
		global_economy["public_tension"] = clamp(
			global_economy["public_tension"] - impact["tension_decrease"], 0, 100)
	if impact.has("senate_alignment_shift"):
		global_economy["senate_alignment"] = clamp(
			global_economy["senate_alignment"] + impact["senate_alignment_shift"], 0, 100)
	if impact.has("price_increase"):
		var sector = impact.get("sector", "")
		if sector == "Food":
			global_economy["food_price"] += impact["price_increase"]
		elif sector in ["Tech", "Pharma"]:
			global_economy["tech_price"] += impact["price_increase"]
	if impact.has("tech_price_increase"):
		global_economy["tech_price"] += impact["tech_price_increase"]
	
	# Optionally generate a NetFeed event from the action
	if action.get("type", "") in ["AMBITION_ACTION", "PR_CAMPAIGN", "PRICE_HIKE"]:
		var event = {
			"type": "NEWS_TICKER",
			"headline": action.get("description", ""),
			"timestamp": Time.get_unix_time_from_system()
		}
		netfeed_history.append(event)
		netfeed_event_generated.emit(event)

# ---------------------------------------------------------
# EVENT HANDLING (The Butterfly Effect)
# ---------------------------------------------------------
func trigger_event(action_id: String, target: String = ""):
	print("World Event Triggered: ", action_id, " on ", target)
	event_triggered.emit(action_id, target)
	
	match action_id:
		"sabotage_facility":
			_ripple_sabotage(target)
		"assassinate_oligarch":
			_ripple_assassination(target)
		"hack_grid":
			_ripple_grid_hack()
		"exert_political_pressure":
			_ripple_political_pressure(target)
		"travel":
			_travel_to_region(target)
		"leak_scandal":
			_ripple_leak_scandal(target)
	
	_update_region_dynamics()
	world_state_changed.emit()
	_check_systemic_collapse()

# --- Ripple Logic ---

func _ripple_sabotage(target_sector: String):
	for o in oligarchs:
		if o.sector_of_influence == target_sector and o.alive:
			o.wealth -= 50000
			o.paranoia += 20
			break
	if target_sector == "Food":
		global_economy["food_price"] += 200
	global_economy["public_tension"] += 15
	global_economy["security_presence"] += 10
	print("Ripple: %s sector sabotaged. Prices spike, tension rises." % target_sector)

func _ripple_assassination(target_id: String):
	for o in oligarchs:
		if o.oligarch_id == target_id and o.alive:
			o.alive = false
			global_economy["public_tension"] += 40
			print("Ripple: %s eliminated. Power vacuum in %s." % [o.oligarch_name, o.sector_of_influence])
			
			# All surviving oligarchs spike paranoia
			for other in oligarchs:
				if other.alive and other.oligarch_id != target_id:
					other.paranoia += 30
					other.awareness_of_player += 40
			
			# If this was a Media oligarch, controversy explodes
			if o.sector_of_influence == "Media":
				for other in oligarchs:
					if other.alive:
						other.controversy_level = 100
			break

func _ripple_grid_hack():
	for o in oligarchs:
		if o.sector_of_influence == "Tech" and o.alive:
			o.wealth -= 10000
			break
	global_economy["security_presence"] = max(0, global_economy["security_presence"] - 20)
	print("Ripple: Grid hacked. Security blinded temporarily.")

func _ripple_political_pressure(target_faction: String):
	if target_faction == "Sinks":
		global_economy["senate_alignment"] -= 10
		global_economy["public_tension"] -= 5
	elif target_faction == "Enclave":
		global_economy["senate_alignment"] += 10
		global_economy["security_presence"] += 5

func _ripple_leak_scandal(target_id: String):
	for o in oligarchs:
		if o.oligarch_id == target_id and o.alive:
			o.public_image = clamp(o.public_image - 30, -100, 100)
			o.controversy_level = clamp(o.controversy_level + 50, 0, 100)
			o.recent_scandals.append("Player leaked classified datashard.")
			print("Ripple: Scandal hits %s. Public image tanks." % o.oligarch_name)
			break

func _travel_to_region(target_region: String):
	if has_node("/root/RegionGenerator"):
		var region_gen = get_node("/root/RegionGenerator")
		var region = region_gen.get_region_by_name(target_region)
		if region.size() > 0 and region.get("unlocked", false):
			current_region = target_region
			print("Traveled to: ", current_region)
		else:
			print("Travel denied. Region locked or invalid.")

func _update_region_dynamics():
	if not has_node("/root/RegionGenerator"):
		return
	var region_gen = get_node("/root/RegionGenerator")
	
	for region in region_gen.regions:
		match region["type"]:
			"URBAN_SLUM":
				if global_economy["food_price"] > 300:
					region["tension_modifier"] = randi_range(30, 50)
			"URBAN_ELITE":
				if global_economy["senate_alignment"] < 30:
					region["security_modifier"] = randi_range(50, 70)

# ---------------------------------------------------------
# PR & REPUTATION ENGINE & THE NETFEED
# ---------------------------------------------------------
func trigger_news_cycle():
	print("--- DAILY NEWS CYCLE (NETFEED REFRESH) ---")
	
	if has_node("/root/LLMManager"):
		var llm = get_node("/root/LLMManager")
		if not llm.netfeed_stream_received.is_connected(_on_netfeed_stream_received):
			llm.netfeed_stream_received.connect(_on_netfeed_stream_received)
		
		# Build oligarch context for the LLM
		var oligarch_context = {}
		for o in oligarchs:
			if o.alive:
				oligarch_context[o.oligarch_name] = {
					"sector": o.sector_of_influence,
					"wealth": o.wealth,
					"paranoia": o.paranoia,
					"public_image": o.public_image,
					"controversy": o.controversy_level,
					"ambitions": o.ambitions,
					"profile": o.get_behavioral_profile()
				}
		
		llm.request_netfeed_events(global_economy, oligarch_context)
	else:
		push_warning("LLMManager not found. Cannot evaluate complex conjectures.")

func _on_netfeed_stream_received(events: Array):
	for event in events:
		event["timestamp"] = Time.get_unix_time_from_system()
		var event_type = event.get("type", "NEWS_TICKER")
		
		if event_type == "NEWS_TICKER":
			netfeed_history.append(event)
			netfeed_event_generated.emit(event)
			print(">>> [PUBLIC NEWS] " + event.get("headline", ""))
		elif event_type == "SILENT_RIPPLE":
			print(">>> [INVISIBLE SHIFT] " + event.get("systemic_impact", ""))

# ---------------------------------------------------------
# QUERIES
# ---------------------------------------------------------

func get_oligarch_by_id(id: String) -> OligarchData:
	for o in oligarchs:
		if o.oligarch_id == id:
			return o
	return null

func get_oligarch_by_sector(sector: String) -> OligarchData:
	for o in oligarchs:
		if o.sector_of_influence == sector and o.alive:
			return o
	return null

func get_living_oligarchs() -> Array[OligarchData]:
	var result: Array[OligarchData] = []
	for o in oligarchs:
		if o.alive:
			result.append(o)
	return result

# ---------------------------------------------------------
# VICTORY CONDITIONS
# ---------------------------------------------------------
func _check_systemic_collapse():
	var all_dead = true
	for o in oligarchs:
		if o.alive:
			all_dead = false
			break
	
	if all_dead:
		print("VICTORY: Direct Action. All Oligarchs eliminated. The Enclave falls.")
	
	if global_economy["public_tension"] >= 100:
		print("VICTORY: Political Revolution. The masses storm The Enclave.")
	
	# Economic collapse: all oligarch wealth below threshold
	var total_wealth = 0
	for o in oligarchs:
		total_wealth += o.wealth
	if total_wealth < 100000 and oligarchs.size() > 0:
		print("VICTORY: Systemic Collapse. The Enclave is bankrupt.")
	
	if global_economy["senate_alignment"] <= 0:
		print("VICTORY: Political Reform. The Senate dissolves corporate charters.")
